#!/usr/bin/env bash
# A script that configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80

# Getting update
sudo apt-get update

# Gettining installation
sudo apt-get install -y nginx

# Give ownership to website files
sudo chown -R ubuntu /var/www

# Create index
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# start nginx service
sudo service nginx start
