#!/usr/bin/env bash
# This script displays the content of the current directoy in a list format,
# showing only the part of the name after the first dash.

for file in *; do
	echo "$file"| cut -d "-" -f2
done
